# Generated by Django 5.2 on 2025-05-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dhhna0y51/image/upload/v1746523943/default_profile_xy7dhb.jpg', upload_to='images/'),
        ),
    ]
